### ISSUE TITLE
Tolerances in `lfpcalc.calc_*_moi` and `lfpcalc.calc_*_anisotropic` methods

### ISSUE THREAD

**Issue by espenhgn** [LFPy/LFPykit#172]
These methods do a bunch of comparisons with very small arbitrary set numbers `some_array >= 1E-9` and similar, presumably to avoid some numerical problems (`ZeroDivisionError` and whatnot). It seems like these statements/methods should be refactored (`assert np.all(some_array > 0)` or equivalent), or at least must take a user-chosen tolerance value as a keyword argument (`atol=some_small_number`). 

@torbjone, since you wrote these and presumably use them, can you please look into this?

There are also a couple of remaining for-loops that look like they could be avoided/vectorized:
```
    for idx in np.where(rs < r_limit)[0]:
        r = rs[idx]
        closest_point = closest_points[:, idx]
        l_vec = l_vecs[:, idx]

        p_ = pos.copy()
        if np.abs(r) < 1e-12:
        ...
```

**Comment by torbjone** [comment]
Sounds like a good idea, I will look into it.

**Comment by espenhgn** [comment]
> Sounds like a good idea, I will look into it.

Thanks!
