### ISSUE TITLE
NY head model wrapper

### ISSUE THREAD

**Issue by espenhgn** [LFPy/LFPykit#51]
Set up class that wraps the lead field of the New York head model (https://www.parralab.org/nyhead/) for EEG predictions.

**Comment by torbjone** [comment]
This could be based on: 
https://github.com/solveignaess/EEG/tree/master/src/compare_head_models

**Comment by espenhgn** [comment]
Yes, that looks useful.

**Comment by espenhgn** [comment]
@torbjone , do you have time to set up such a wrapper? If not, I don't mind pushing this back to a future version 0.2 to not delay release 0.1.

**Comment by torbjone** [comment]
I can probably get this done next week.
