### ISSUE TITLE
rename `get_response_matrix()` method `get_transformation_matrix`

### ISSUE THREAD

**Issue by espenhgn** [LFPy/LFPykit#55]
Up for discussion; each forward-model like class should have a public method `get_response_matrix()`. 
Should this be renamed or fine as is? Some libraries use `get_transfer_resistance` (or similar), but that doesn't make sense for class `CurrentDipoleMoment`  for instance.

**Comment by torbjone** [comment]
How about get_transfer_matrix ?

**Comment by espenhgn** [comment]
`get_transfer_matrix` sounded alright to me, but I think "transformation matrix" is the more general term: https://en.wikipedia.org/wiki/Transformation_matrix 

So `get_transformation_matrix` perhaps? The term "transfer matrix" refers to something specific: https://en.wikipedia.org/wiki/Transfer_matrix
